###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "420skun@gmail.com",
    "password": "Abc123"
}

###

GET http://localhost:3000/verification?token=177afe741016d2d17db1aeae6a411aec7ab66257

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "420skun@gmail.com",
    "password": "Abc123"
}

###

GET http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzksImVtYWlsIjoiNDIwc2t1bkBnbWFpbC5jb20iLCJyb2xlIjoxLCJmaXJzdF9uYW1lIjpudWxsLCJpYXQiOjE3MjM1MDQ3NjksImV4cCI6MTc1NTA0MDc2OX0.OvFzB3xVJiFfRtAYfmfiVeM9wj1GM_QxquCy8tsHo0I